"""createDate update namechanged

Revision ID: 5048ea0c3825
Revises: a46f28786858
Create Date: 2026-08-25 02:22:01.672110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5048ea0c3825'
down_revision: Union[str, Sequence[str], None] = 'a46f28786858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings',column_name='create_date',new_column_name="createDate" )
    op.alter_column('bookings',column_name='update_date',new_column_name="updateDate")
  
    op.alter_column('cars', column_name='create_date',new_column_name="createDate" )
    op.alter_column('cars', column_name='update_date',new_column_name="updateDate")

    op.alter_column('expenses', column_name='create_date',new_column_name="createDate" )
    op.alter_column('expenses', column_name='update_date',new_column_name="updateDate")

    op.alter_column('profiles', column_name='create_date',new_column_name="createDate" )
    op.alter_column('profiles', column_name='update_date',new_column_name="updateDate")
    op.alter_column('users', column_name='create_date',new_column_name="createDate" )
    op.alter_column('users', column_name='update_date',new_column_name="updateDate")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', column_name="createDate",new_column_name="create_date")
    op.alter_column('users', column_name="updateDate",new_column_name="update_date")
    op.alter_column('profiles', column_name="createDate",new_column_name="create_date")
    op.alter_column('profiles',  column_name="updateDate",new_column_name="update_date")
    op.alter_column('expenses', column_name="createDate",new_column_name="create_date")
    op.alter_column('expenses',  column_name="updateDate",new_column_name="update_date")
    op.alter_column('cars', column_name="createDate",new_column_name="create_date")
    op.alter_column('cars',  column_name="updateDate",new_column_name="update_date")
    op.alter_column('bookings', column_name="createDate",new_column_name="create_date")
    op.alter_column('bookings',  column_name="updateDate",new_column_name="update_date")
    # ### end Alembic commands ###
