"""car model phoneNumber Key changed

Revision ID: 86a2dc8d22f6
Revises: 5048ea0c3825
Create Date: 2026-08-31 17:37:32.295551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a2dc8d22f6'
down_revision: Union[str, Sequence[str], None] = '5048ea0c3825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars',new_column_name='driverPhoneNumber',column_name='driverphoneNumber')
  
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars',new_column_name='driverphoneNumber',column_name='driverPhoneNumber')
  
    # ### end Alembic commands ###
