"""initial tables

Revision ID: a46f28786858
Revises: 
Create Date: 2026-08-24 19:18:28.439430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46f28786858'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('localId', sa.String(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('localCreateDate', sa.BigInteger(), nullable=True),
    sa.Column('localUpdateDate', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.BigInteger(), nullable=False),
    sa.Column('update_date', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('localId')
    )
    op.create_table('users',
    sa.Column('phoneNumber', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.BigInteger(), nullable=False),
    sa.Column('update_date', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=True)
    op.create_table('bookings',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('localId', sa.String(), nullable=False),
    sa.Column('carName', sa.String(length=100), nullable=False),
    sa.Column('carNumber', sa.String(length=100), nullable=False),
    sa.Column('customerName', sa.String(length=500), nullable=False),
    sa.Column('customerPhoneNumber', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('bookingDate', sa.BigInteger(), nullable=False),
    sa.Column('fromStation', sa.String(), nullable=False),
    sa.Column('toStation', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('carLocalId', sa.String(), nullable=True),
    sa.Column('localCreateDate', sa.BigInteger(), nullable=False),
    sa.Column('localUpdateDate', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.BigInteger(), nullable=False),
    sa.Column('update_date', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'localId', name='uq_booking_user_local_id')
    )
    op.create_index(op.f('ix_bookings_userId'), 'bookings', ['userId'], unique=False)
    op.create_table('cars',
    sa.Column('localId', sa.String(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('carNumber', sa.String(), nullable=False),
    sa.Column('carBrandName', sa.String(), nullable=False),
    sa.Column('isAc', sa.Boolean(), nullable=False),
    sa.Column('tripType', sa.String(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('driverName', sa.String(), nullable=True),
    sa.Column('driverphoneNumber', sa.String(), nullable=True),
    sa.Column('withDriverPerKmPrice', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('withDriverPerDayPrice', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('withoutDriverPerKmPrice', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('withoutDriverPerDayPrice', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('localCreateDate', sa.BigInteger(), nullable=False),
    sa.Column('localUpdateDate', sa.BigInteger(), nullable=False),
    sa.Column('coverImageUrl', sa.String(length=500), nullable=True),
    sa.Column('frontImageUrl', sa.String(length=500), nullable=True),
    sa.Column('backImageUrl', sa.String(length=500), nullable=True),
    sa.Column('leftImageUrl', sa.String(length=500), nullable=True),
    sa.Column('rightImageUrl', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.BigInteger(), nullable=False),
    sa.Column('update_date', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('localId'),
    sa.UniqueConstraint('userId', 'localId', name='uq_car_user_local_id')
    )
    op.create_index(op.f('ix_cars_userId'), 'cars', ['userId'], unique=False)
    op.create_table('profiles',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('ownerName', sa.String(length=100), nullable=True),
    sa.Column('companyName', sa.String(length=150), nullable=True),
    sa.Column('logoImageUrl', sa.String(), nullable=True),
    sa.Column('aboutCompany', sa.String(length=10000), nullable=True),
    sa.Column('companyWebsite', sa.String(length=500), nullable=True),
    sa.Column('instagramProfile', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.BigInteger(), nullable=False),
    sa.Column('update_date', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_userId'), 'profiles', ['userId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_userId'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_cars_userId'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_bookings_userId'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.drop_table('users')
    op.drop_table('expenses')
    # ### end Alembic commands ###
