"""few tables addded and authwith email added

Revision ID: ff9616baff1b
Revises: 86a2dc8d22f6
Create Date: 2026-09-18 08:14:57.739392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9616baff1b'
down_revision: Union[str, Sequence[str], None] = '86a2dc8d22f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phoneNumber', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'phoneNumber')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phoneNumber', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=True)
    op.drop_column('users', 'email')
    op.drop_column('profiles', 'phoneNumber')
    # ### end Alembic commands ###
