name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - maindev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd ~/carbooking_backend

            echo "===== BEFORE UPDATE ====="
            git rev-parse HEAD

            echo "===== FETCHING LATEST CODE ====="
            git fetch origin maindev

            echo "===== RESETTING TO ORIGIN/MAINDEV ====="
            git reset --hard origin/maindev

            echo "===== AFTER UPDATE ====="
            git rev-parse HEAD

            echo "===== REBUILDING DOCKER ====="
            docker compose up -d --build

            echo "===== CONTAINERS ====="
            docker compose ps